export type AccountingDimensionsErrorCode =
  | "PERMISSION_DENIED"
  | "DIMENSION_REPOSITORIES_NOT_CONFIGURED"
  | "DIMENSION_TYPE_NOT_FOUND"
  | "DIMENSION_MEMBER_NOT_FOUND"
  | "DIMENSION_POLICY_NOT_FOUND"
  | "ACCOUNT_NOT_FOUND"
  | "DUPLICATE_DIMENSION_TYPE_CODE"
  | "DUPLICATE_DIMENSION_MEMBER_CODE"
  | "DUPLICATE_ACCOUNT_DIMENSION_POLICY"
  | "DIMENSION_TYPE_NOT_HIERARCHICAL"
  | "DIMENSION_MEMBER_PARENT_MISMATCH"
  | "DIMENSION_MEMBER_TREE_CYCLE"
  | "DIMENSION_TYPE_HAS_MEMBERS"
  | "DIMENSION_TYPE_HAS_POLICIES"
  | "DIMENSION_TYPE_IN_USE"
  | "DIMENSION_MEMBER_HAS_CHILDREN"
  | "DIMENSION_MEMBER_HAS_ACTIVE_CHILDREN"
  | "DIMENSION_MEMBER_IN_USE"
  | "DIMENSION_TYPE_HAS_ACTIVE_MEMBERS"
  | "ACCOUNT_INACTIVE"
  | "DIMENSION_TYPE_INACTIVE"
  | "VERSION_MISMATCH";

export class AccountingDimensionsError extends Error {
  constructor(
    readonly code: AccountingDimensionsErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "AccountingDimensionsError";
  }
}
