import type { GeneratedNumber, NumberSeries, NumberSeriesDefinition, NumberSeriesRequest } from "@argin/platform";
import { createNumberSeriesScopeKey } from "@argin/platform";
import { INVENTORY_DOCUMENT_TYPES } from "../domain/inventory-document.ts";
import type { InventoryDocumentSnapshot, InventoryDocumentType } from "../domain/inventory-document.ts";
import { InventoryDomainError, INVENTORY_DOMAIN_ERROR_CODES as codes } from "../domain/inventory-errors.ts";
import { validateInventoryDocumentScope } from "./inventory-scope-validation.ts";
import type { InventoryScopeContext, InventoryScopeReaders } from "./inventory-scope-validation.ts";

export const INVENTORY_NUMBER_SERIES_TYPES: Readonly<Record<InventoryDocumentType, string>> = Object.freeze({
  receipt: "inventory.receipt", issue: "inventory.issue", opening: "inventory.opening",
  transfer: "inventory.transfer", adjustment: "inventory.adjustment",
});
export const DEFAULT_INVENTORY_NUMBER_SERIES_DEFINITIONS: readonly NumberSeriesDefinition[] = Object.freeze(
  INVENTORY_DOCUMENT_TYPES.map(type => Object.freeze({ seriesType: INVENTORY_NUMBER_SERIES_TYPES[type], initialValue: 1, incrementBy: 1, padding: 6, prefix: "", suffix: "" })),
);
export interface InventoryNumberReservation extends GeneratedNumber { readonly documentId: string; }

/**
 * Reserve only after current scope checks. Call inside the future document UoW,
 * after the durable idempotency lookup; this helper neither saves nor retries a document.
 */
export async function reserveInventoryDocumentNumber(
  numberSeries: NumberSeries,
  input: InventoryDocumentSnapshot,
  context: InventoryScopeContext,
  readers: InventoryScopeReaders,
): Promise<InventoryNumberReservation> {
  // Avoid reserving again for a document that already has a display number.
  if (input?.documentNumber != null) throw new InventoryDomainError(codes.numberAlreadyAssigned, "documentNumber");
  const document = await validateInventoryDocumentScope(input, context, readers);
  const expected: NumberSeriesRequest = Object.freeze({
    seriesType: INVENTORY_NUMBER_SERIES_TYPES[document.documentType],
    scope: Object.freeze({ companyId: document.companyId, fiscalYearId: document.scope.fiscalYearId,
      ...(document.scope.branchId === null ? {} : { branchId: document.scope.branchId }) }),
  });
  const result = await numberSeries.next(expected);
  if (!result || result.seriesType !== expected.seriesType || !result.scope ||
      result.scope.companyId !== expected.scope.companyId || result.scope.branchId !== expected.scope.branchId ||
      result.scope.fiscalYearId !== expected.scope.fiscalYearId ||
      !Number.isSafeInteger(result.sequence) || result.sequence < 1 || typeof result.formattedValue !== "string" || !result.formattedValue.trim()) {
    throw new InventoryDomainError(codes.numberResultInvalid, "numberSeries");
  }
  // Scope keys are generated by the shared engine, not a second inventory counter implementation.
  if (createNumberSeriesScopeKey(result.scope) !== createNumberSeriesScopeKey(expected.scope)) throw new InventoryDomainError(codes.numberResultInvalid, "numberSeries.scope");
  return Object.freeze({ documentId: document.documentId, seriesType: expected.seriesType, scope: expected.scope,
    sequence: result.sequence, formattedValue: result.formattedValue });
}
