import { normalizeAccountingDimensionMemberSearchQuery, type AccountingDimensionMember, type AccountingDimensionMemberRepository, type AccountingDimensionMemberSearchQuery, type AccountingDimensionMemberSortField } from "@argin/accounting";
import { assertVersionedUpdate, type DatabaseSession } from "@argin/database";
import { queryPage, sqlOrderBy } from "./sqlite-dimension-query.ts";
interface Row { id:string;company_id:string;dimension_type_id:string;code:string;name:string;english_name:string|null;parent_id:string|null;status:AccountingDimensionMember["status"];valid_from:string|null;valid_to:string|null;display_order:number;source:AccountingDimensionMember["source"];source_reference_id:string|null;created_at:string;updated_at:string;version:number }
const columns:Record<AccountingDimensionMemberSortField,string>={displayOrder:"display_order",code:"code",name:"name",validFrom:"valid_from",createdAt:"created_at",id:"id"};
const map=(r:Row):AccountingDimensionMember=>Object.freeze({id:r.id,companyId:r.company_id,dimensionTypeId:r.dimension_type_id,code:r.code,name:r.name,englishName:r.english_name,parentId:r.parent_id,status:r.status,validFrom:r.valid_from,validTo:r.valid_to,displayOrder:r.display_order,source:r.source,sourceReferenceId:r.source_reference_id,createdAt:r.created_at,updatedAt:r.updated_at,version:r.version});
export class SqliteAccountingDimensionMemberRepository implements AccountingDimensionMemberRepository {
 constructor(private readonly database:DatabaseSession){}
 async create(v:AccountingDimensionMember):Promise<void>{await this.database.execute(`INSERT INTO accounting_dimension_members (id,company_id,dimension_type_id,code,name,english_name,parent_id,status,valid_from,valid_to,display_order,source,source_reference_id,created_at,updated_at,version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,this.params(v));}
 async findById(id:string){const r=await this.database.queryOne<Row>(`SELECT * FROM accounting_dimension_members WHERE id=?`,[id]);return r?map(r):null;}
 async findByCode(companyId:string,typeId:string,code:string){const r=await this.database.queryOne<Row>(`SELECT * FROM accounting_dimension_members WHERE company_id=? AND dimension_type_id=? AND code=? COLLATE NOCASE`,[companyId,typeId,code]);return r?map(r):null;}
 async findChildren(companyId:string,parentId:string){const r=await this.database.query<Row>(`SELECT * FROM accounting_dimension_members WHERE company_id=? AND parent_id=? ORDER BY display_order, code, id`,[companyId,parentId]);return r.map(map);}
 async search(input:AccountingDimensionMemberSearchQuery){const q=normalizeAccountingDimensionMemberSearchQuery(input),w=["company_id = ?"],p:(string|number|null)[]=[q.companyId];if(q.dimensionTypeId){w.push("dimension_type_id = ?");p.push(q.dimensionTypeId);}if(q.status){w.push("status = ?");p.push(q.status);}if(q.parentId!==undefined){w.push(q.parentId===null?"parent_id IS NULL":"parent_id = ?");if(q.parentId!==null)p.push(q.parentId);}if(q.effectiveOn){w.push("(valid_from IS NULL OR valid_from <= ?)","(valid_to IS NULL OR valid_to >= ?)");p.push(q.effectiveOn,q.effectiveOn);}if(q.text){w.push("(code LIKE ? ESCAPE '\\' OR name LIKE ? ESCAPE '\\' OR english_name LIKE ? ESCAPE '\\')");const x=`%${q.text.replace(/[\\%_]/g,"\\$&")}%`;p.push(x,x,x);}return queryPage<Row,AccountingDimensionMember>(this.database,"accounting_dimension_members",w,p,sqlOrderBy(q.sorts,columns),q.pagination,map);}
 async update(v:AccountingDimensionMember):Promise<void>{const x=await this.database.execute(`UPDATE accounting_dimension_members SET dimension_type_id=?,code=?,name=?,english_name=?,parent_id=?,status=?,valid_from=?,valid_to=?,display_order=?,source=?,source_reference_id=?,updated_at=?,version=? WHERE id=? AND company_id=? AND version=?`,[v.dimensionTypeId,v.code,v.name,v.englishName,v.parentId,v.status,v.validFrom,v.validTo,v.displayOrder,v.source,v.sourceReferenceId,v.updatedAt,v.version,v.id,v.companyId,v.version-1]);assertVersionedUpdate(x,{entityType:"AccountingDimensionMember",entityId:v.id,expectedVersion:v.version-1});}
 async delete(v:AccountingDimensionMember):Promise<void>{const x=await this.database.execute(`DELETE FROM accounting_dimension_members WHERE id=? AND company_id=? AND version=?`,[v.id,v.companyId,v.version]);assertVersionedUpdate(x,{entityType:"AccountingDimensionMember",entityId:v.id,expectedVersion:v.version});}
 private params(v:AccountingDimensionMember){return[v.id,v.companyId,v.dimensionTypeId,v.code,v.name,v.englishName,v.parentId,v.status,v.validFrom,v.validTo,v.displayOrder,v.source,v.sourceReferenceId,v.createdAt,v.updatedAt,v.version];}
}
