import { normalizeAccountDimensionPolicySearchQuery, type AccountDimensionPolicy, type AccountDimensionPolicyRepository, type AccountDimensionPolicySearchQuery, type AccountDimensionPolicySortField } from "@argin/accounting";
import { assertVersionedUpdate, type DatabaseSession } from "@argin/database";
import { queryPage, sqlOrderBy } from "./sqlite-dimension-query.ts";
interface Row{id:string;company_id:string;account_id:string;dimension_type_id:string;requirement:AccountDimensionPolicy["requirement"];created_at:string;updated_at:string;version:number}
const columns:Record<AccountDimensionPolicySortField,string>={accountId:"account_id",dimensionTypeId:"dimension_type_id",requirement:"requirement",createdAt:"created_at",id:"id"};
const map=(r:Row):AccountDimensionPolicy=>Object.freeze({id:r.id,companyId:r.company_id,accountId:r.account_id,dimensionTypeId:r.dimension_type_id,requirement:r.requirement,createdAt:r.created_at,updatedAt:r.updated_at,version:r.version});
export class SqliteAccountDimensionPolicyRepository implements AccountDimensionPolicyRepository{
 constructor(private readonly database:DatabaseSession){}
 async create(v:AccountDimensionPolicy):Promise<void>{await this.database.execute(`INSERT INTO account_dimension_policies (id,company_id,account_id,dimension_type_id,requirement,created_at,updated_at,version) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,this.params(v));}
 async findById(id:string){const r=await this.database.queryOne<Row>(`SELECT * FROM account_dimension_policies WHERE id=?`,[id]);return r?map(r):null;}
 async findByAccountAndType(companyId:string,accountId:string,typeId:string){const r=await this.database.queryOne<Row>(`SELECT * FROM account_dimension_policies WHERE company_id=? AND account_id=? AND dimension_type_id=?`,[companyId,accountId,typeId]);return r?map(r):null;}
 async findByAccountId(companyId:string,accountId:string){const r=await this.database.query<Row>(`SELECT * FROM account_dimension_policies WHERE company_id=? AND account_id=? ORDER BY dimension_type_id, id`,[companyId,accountId]);return r.map(map);}
 async search(input:AccountDimensionPolicySearchQuery){const q=normalizeAccountDimensionPolicySearchQuery(input),w=["company_id = ?"],p:string[]=[q.companyId];if(q.accountId){w.push("account_id = ?");p.push(q.accountId);}if(q.dimensionTypeId){w.push("dimension_type_id = ?");p.push(q.dimensionTypeId);}if(q.requirement){w.push("requirement = ?");p.push(q.requirement);}return queryPage<Row,AccountDimensionPolicy>(this.database,"account_dimension_policies",w,p,sqlOrderBy(q.sorts,columns),q.pagination,map);}
 async update(v:AccountDimensionPolicy):Promise<void>{const x=await this.database.execute(`UPDATE account_dimension_policies SET account_id=?,dimension_type_id=?,requirement=?,updated_at=?,version=? WHERE id=? AND company_id=? AND version=?`,[v.accountId,v.dimensionTypeId,v.requirement,v.updatedAt,v.version,v.id,v.companyId,v.version-1]);assertVersionedUpdate(x,{entityType:"AccountDimensionPolicy",entityId:v.id,expectedVersion:v.version-1});}
 async delete(v:AccountDimensionPolicy):Promise<void>{const x=await this.database.execute(`DELETE FROM account_dimension_policies WHERE id=? AND company_id=? AND version=?`,[v.id,v.companyId,v.version]);assertVersionedUpdate(x,{entityType:"AccountDimensionPolicy",entityId:v.id,expectedVersion:v.version});}
 private params(v:AccountDimensionPolicy){return[v.id,v.companyId,v.accountId,v.dimensionTypeId,v.requirement,v.createdAt,v.updatedAt,v.version];}
}
