import { calculateSalesLineTotals, type SalesDocumentSnapshot, type SalesDocumentStatus } from "@argin/sales";
import { createInventoryXlsx } from "@argin/inventory-tauri";
export interface SalesOutputDocument extends SalesDocumentSnapshot { readonly status: SalesDocumentStatus; }
export interface SalesPrintModel { readonly title:string;readonly fileStem:string;readonly orientation:"landscape";readonly metadata:readonly {label:string;value:string}[];readonly columns:readonly {label:string;numeric?:boolean}[];readonly rows:readonly (readonly string[])[];readonly footer:readonly string[]; }
const TYPES:Record<SalesDocumentSnapshot["documentType"],string>={"sales-order":"سفارش فروش","sales-invoice":"فاکتور فروش","sales-return":"برگشت از فروش","sales-correction":"اصلاح فروش"};
const STATUSES:Record<SalesDocumentStatus,string>={draft:"پیش‌نویس",submitted:"ارسال‌شده",approved:"تأییدشده",finalized:"قطعی",cancelled:"لغوشده"};
export function createSalesPrintModel(input:{document:SalesOutputDocument;companyName:string;branchName:string}):SalesPrintModel{
 const d=input.document, totals=d.lines.map(x=>x.commercialTerms?calculateSalesLineTotals(x.commercialTerms):null),currency=d.lines.find(x=>x.commercialTerms)?.commercialTerms?.currency??"IRR";
 const sum=(key:"grossAmount"|"discountAmount"|"taxAmount"|"grandTotal")=>totals.reduce((n,t)=>n+(t?.[key]??0),0);
 return Object.freeze({title:TYPES[d.documentType],fileStem:safe(TYPES[d.documentType]+"-"+(d.documentNumber??d.documentId)),orientation:"landscape" as const,metadata:Object.freeze([
  {label:"شرکت",value:input.companyName},{label:"شعبه",value:input.branchName},{label:"شماره سند",value:d.documentNumber??"پیش‌نویس"},{label:"تاریخ",value:new Intl.DateTimeFormat("fa-IR-u-ca-persian").format(new Date(d.businessDate+"T12:00:00"))},{label:"مشتری",value:d.customer.code+" — "+d.customer.displayName},{label:"وضعیت",value:STATUSES[d.status]},{label:"توضیحات",value:d.description??"—"}]),
 columns:Object.freeze([{label:"ردیف",numeric:true},{label:"کالا / خدمت"},{label:"نوع"},{label:"تعداد",numeric:true},{label:"قیمت واحد",numeric:true},{label:"تخفیف",numeric:true},{label:"مالیات",numeric:true},{label:"جمع",numeric:true}]),
 rows:Object.freeze(d.lines.map(line=>{const t=line.commercialTerms?calculateSalesLineTotals(line.commercialTerms):null;return Object.freeze([String(line.position),line.description||line.item.productId,line.lineKind==="service"?"خدمت":"کالا",String(line.commercialTerms?.quantity??""),money(line.commercialTerms?.unitPrice??0),money(t?.discountAmount??0),money(t?.taxAmount??0),money(t?.grandTotal??0)]);})),
 footer:Object.freeze(["","","","",currency+" "+money(sum("grossAmount")),money(sum("discountAmount")),money(sum("taxAmount")),currency+" "+money(sum("grandTotal"))])});
}
export function downloadSalesXlsx(model:SalesPrintModel):void{const rows=model.rows.map(row=>Object.fromEntries(model.columns.map((c,i)=>[c.label,row[i]??""])));download(createInventoryXlsx(rows,model.title),model.fileStem+".xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");}
export function openSalesPrintPreview(model:SalesPrintModel):void{const doc=document;doc.getElementById("sales-print-preview")?.remove();const old=doc.body.style.overflow;doc.body.style.overflow="hidden";const overlay=doc.createElement("div");overlay.id="sales-print-preview";overlay.dir="rtl";overlay.tabIndex=-1;overlay.setAttribute("role","dialog");overlay.setAttribute("aria-modal","true");Object.assign(overlay.style,{position:"fixed",inset:"0",zIndex:"2147483647",display:"grid",gridTemplateRows:"56px minmax(0,1fr)",background:"#e2e8f0"});const bar=doc.createElement("div");Object.assign(bar.style,{display:"flex",alignItems:"center",gap:"8px",padding:"8px 16px",background:"#fff",fontFamily:"Vazirmatn,Tahoma,sans-serif"});const title=doc.createElement("strong");title.textContent="پیش‌نمایش چاپ — "+model.title;title.style.marginInlineEnd="auto";const print=button("چاپ / ذخیره PDF"),close=button("بستن"),frame=doc.createElement("iframe");frame.srcdoc=createSalesPrintHtml(model);frame.title="پیش‌نمایش "+model.title;Object.assign(frame.style,{width:"100%",height:"100%",border:"0",background:"#fff"});const dismiss=()=>{overlay.remove();doc.body.style.overflow=old;};print.onclick=()=>printSales(model);close.onclick=dismiss;overlay.onkeydown=e=>{if(e.key==="Escape")dismiss();};bar.append(title,print,close);overlay.append(bar,frame);doc.body.append(overlay);overlay.focus();}
export function createSalesPrintHtml(model:SalesPrintModel):string{const heads=model.columns.map(c=>cell("th",c.label,c.numeric)).join(""),rows=model.rows.map(r=>"<tr>"+r.map((v,i)=>cell("td",v,model.columns[i]?.numeric)).join("")+"</tr>").join(""),foot=model.footer.map((v,i)=>cell("th",v,model.columns[i]?.numeric)).join(""),meta=model.metadata.map(x=>"<span><b>"+esc(x.label)+":</b> "+esc(x.value)+"</span>").join("");return "<!doctype html><html lang=\"fa\" dir=\"rtl\"><head><meta charset=\"utf-8\"><title>"+esc(model.title)+"</title><style>"+printCss+"</style></head><body><header><h1>"+esc(model.title)+"</h1><div class=\"meta\">"+meta+"</div></header><table><thead><tr>"+heads+"</tr></thead><tbody>"+rows+"</tbody><tfoot><tr>"+foot+"</tr></tfoot></table></body></html>";}
function printSales(model:SalesPrintModel){const w=window.open("","_blank");if(!w)throw new Error("مرورگر اجازه بازکردن پنجره چاپ را نداد.");w.document.write(createSalesPrintHtml(model));w.document.close();w.onload=()=>{w.focus();w.print();};}
const printCss="@page{size:A4 landscape;margin:10mm}*{box-sizing:border-box}body{margin:0;padding:8mm;direction:rtl;font-family:Vazirmatn,Tahoma,Arial,sans-serif;color:#111827;font-size:9pt}header{display:grid;gap:3mm;margin-bottom:5mm;border-bottom:1px solid #94a3b8;padding-bottom:4mm}h1{margin:0;font-size:16pt}.meta{display:flex;flex-wrap:wrap;gap:2mm 6mm;color:#475569}table{width:100%;border-collapse:collapse}thead{display:table-header-group}tr{page-break-inside:avoid}th,td{border:1px solid #cbd5e1;padding:1.6mm 2mm;text-align:right}th{background:#f1f5f9}.num{direction:ltr;text-align:left;font-variant-numeric:tabular-nums;white-space:nowrap}@media print{body{padding:0;font-size:8.5pt}}";
const cell=(tag:"th"|"td",v:string,n?:boolean)=>"<"+tag+(n?" class=\"num\"":"")+">"+esc(v)+"</"+tag+">";const money=(n:number)=>new Intl.NumberFormat("fa-IR").format(n);const safe=(s:string)=>s.replace(/[\\/:*?\"<>|]+/g,"-").trim()||"sales";const esc=(s:string)=>s.replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
function button(label:string){const b=document.createElement("button");b.type="button";b.textContent=label;Object.assign(b.style,{border:"1px solid #cbd5e1",borderRadius:"8px",background:"#fff",padding:"8px 12px",cursor:"pointer"});return b;}
function download(bytes:Uint8Array,name:string,mime:string){const url=URL.createObjectURL(new Blob([new Uint8Array(bytes).buffer],{type:mime})),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}