import { useEffect, useMemo, useState } from "react";
import { getDesktopDatabase } from "@argin/database-tauri";
import type { InventoryValuationAsOfReport, InventoryValuationLayerReport, InventoryValuationMonetaryKardexReport, InventoryValuationRecalculationStatusReport, InventoryValuationUnresolvedReport } from "@argin/inventory/valuation-reports";
import type { InventoryValuationPolicySnapshot } from "@argin/inventory/valuation-policy";
import type { InventoryValuationTraceSnapshot } from "@argin/inventory/valuation-security";
import type { ProductSelectorItemDto } from "@argin/product";
import type { WarehouseListItemDto } from "@argin/warehouse";
import { useActiveContext } from "../../app/providers/active-context-provider";
import { useAuthSession } from "../../app/providers/auth-session-provider";
import { Feedback } from "../../components/feedback";
import { Page } from "../../components/layout";
import { createInventoryValuationServices, type InventoryValuationServices } from "../../composition/inventory/create-inventory-valuation-services";
import { createInventoryValuationTraceService } from "../../composition/inventory/create-inventory-valuation-trace-service";
import { gregorianToJalali, jalaliToGregorian } from "./inventory-persian-date";
import { ValuationKardexPanel, ValuationLayersPanel, ValuationOverviewPanel, ValuationPolicyPanel, ValuationTracePanel, ValuationUnresolvedPanel } from "./inventory-valuation-panels";
import "./inventory-valuation-workspace-page.css";

type Tab="overview"|"kardex"|"layers"|"unresolved"|"policy";
const today=()=>gregorianToJalali(new Date().toISOString().slice(0,10));

export function InventoryValuationWorkspacePage(){
  const active=useActiveContext(); const {session}=useAuthSession();
  const [services,setServices]=useState<InventoryValuationServices|null>(null); const [traceReader,setTraceReader]=useState<((companyId:string,movementId:string)=>Promise<InventoryValuationTraceSnapshot|null>)|null>(null);
  const [tab,setTab]=useState<Tab>("overview"); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  const [products,setProducts]=useState<readonly ProductSelectorItemDto[]>([]); const [warehouses,setWarehouses]=useState<readonly WarehouseListItemDto[]>([]); const [productId,setProductId]=useState(""); const [warehouseId,setWarehouseId]=useState(""); const [asOf,setAsOf]=useState(today()); const [from,setFrom]=useState(""); const [to,setTo]=useState(today());
  const [overview,setOverview]=useState<InventoryValuationAsOfReport|null>(null); const [kardex,setKardex]=useState<InventoryValuationMonetaryKardexReport|null>(null); const [layers,setLayers]=useState<InventoryValuationLayerReport|null>(null); const [unresolved,setUnresolved]=useState<InventoryValuationUnresolvedReport|null>(null); const [status,setStatus]=useState<InventoryValuationRecalculationStatusReport|null>(null); const [policies,setPolicies]=useState<readonly InventoryValuationPolicySnapshot[]>([]); const [trace,setTrace]=useState<InventoryValuationTraceSnapshot|null>(null);
  const actor=useMemo(()=>({permissions:session?.user.permissions??[],branchIds:session?.user.branchIds??[]}),[session]);

  useEffect(()=>{void getDesktopDatabase().then(db=>{setServices(createInventoryValuationServices({database:db,actor}));setTraceReader(()=>createInventoryValuationTraceService(db));}).catch(e=>setError(e instanceof Error?e.message:"راه‌اندازی ارزش‌گذاری ناموفق بود."));},[actor]);
  useEffect(()=>{if(!services?.canView||!active.companyId)return;void Promise.all([services.selectProducts(active.companyId),services.selectWarehouses(active.companyId,active.branchId||null)]).then(([p,w])=>{setProducts(p);setWarehouses(w);}).catch(e=>setError(e instanceof Error?e.message:"بارگذاری انتخابگرها ناموفق بود."));},[services,active.companyId,active.branchId]);

  async function load(next:Tab=tab,cursor:string|null=null){if(!services||!active.companyId)return;setLoading(true);setError("");setTrace(null);try{const companyId=active.companyId,branchId=active.branchId||null;if(next==="overview"){setOverview(await services.readAsOf({companyId,branchId,asOfBusinessDate:jalaliToGregorian(asOf),productId:productId||null,warehouseId:warehouseId||null,limit:100}));setStatus(await services.readStatus(companyId,productId||null));}else if(next==="kardex"){if(!productId||!warehouseId)throw new Error("برای کاردکس ریالی، کالا و انبار را انتخاب کنید.");setKardex(await services.readKardex({companyId,branchId,productId,warehouseId,businessDateFrom:from?jalaliToGregorian(from):null,businessDateTo:to?jalaliToGregorian(to):null,cursor,limit:100}));}else if(next==="layers")setLayers(await services.readLayers({companyId,branchId,productId:productId||null,warehouseId:warehouseId||null,onlyOpen:true,limit:100}));else if(next==="unresolved")setUnresolved(await services.readUnresolved({companyId,branchId,productId:productId||null,warehouseId:warehouseId||null,fromBusinessDate:from?jalaliToGregorian(from):null,limit:100}));else setPolicies(await services.getPolicyHistory(companyId));setTab(next);}catch(e){setError(e instanceof Error?e.message:"خواندن ارزش‌گذاری ناموفق بود.");}finally{setLoading(false);}}
  useEffect(()=>{if(services?.canView&&active.companyId)void load("overview");},[services,active.companyId]);
  async function openTrace(id:string){if(traceReader&&active.companyId)setTrace(await traceReader(active.companyId,id));}
  if(services&&!services.canView)return <Page><Feedback tone="error">برای مشاهده ارزش‌گذاری موجودی مجوز کافی ندارید.</Feedback></Page>;

  return <Page className="valuation-page" dir="rtl"><header className="valuation-head"><div><h2>ارزش‌گذاری موجودی</h2><p>ارزش ریالی، کاردکس مالی، FIFO، موارد حل‌نشده و تاریخچه سیاست.</p></div><div className={`valuation-status valuation-status--${status?.status??"empty"}`}>{status?.status==="current"?"به‌روز":status?.status==="attention-required"?"نیازمند بررسی":"بدون گردش"}<small>Revision: <bdi>{status?.streamRevision??0}</bdi></small></div></header>{error&&<Feedback tone="error">{error}</Feedback>}<p className="valuation-note"><strong>پل آرگین:</strong> Movement، Cost Input و Policy داده اصلی‌اند؛ جمع گزارش و مانده ریالی خروجی بازسازی‌پذیر هستند.</p><div className="valuation-tabs">{([['overview','ارزش موجودی'],['kardex','کاردکس ریالی'],['layers','لایه‌های FIFO'],['unresolved','نیازمند بررسی'],['policy','سیاست ارزش‌گذاری']] as const).map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>void load(k)}>{l}</button>)}</div><div className="valuation-filters"><label>کالا<select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">همه کالاها</option>{products.map(p=><option key={p.productId} value={p.productId}>{p.code} — {p.title}</option>)}</select></label><label>انبار<select value={warehouseId} onChange={e=>setWarehouseId(e.target.value)}><option value="">همه انبارها</option>{warehouses.map(w=><option key={w.warehouseId} value={w.warehouseId}>{w.code} — {w.title}</option>)}</select></label>{tab==="overview"&&<label>تا تاریخ<input dir="ltr" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label>}{(tab==="kardex"||tab==="unresolved")&&<label>از تاریخ<input dir="ltr" value={from} onChange={e=>setFrom(e.target.value)}/></label>}{tab==="kardex"&&<label>تا تاریخ<input dir="ltr" value={to} onChange={e=>setTo(e.target.value)}/></label>}<button disabled={loading} onClick={()=>void load()}>{loading?"در حال خواندن…":"اعمال فیلتر"}</button></div>{tab==="overview"&&overview&&<ValuationOverviewPanel report={overview}/>} {tab==="kardex"&&kardex&&<ValuationKardexPanel report={kardex} onTrace={id=>void openTrace(id)} onNext={cursor=>void load("kardex",cursor)}/>} {tab==="layers"&&layers&&<ValuationLayersPanel report={layers}/>} {tab==="unresolved"&&unresolved&&<ValuationUnresolvedPanel report={unresolved}/>} {tab==="policy"&&<ValuationPolicyPanel rows={policies} readOnly={!services?.canManagePolicy}/>} {trace&&<ValuationTracePanel trace={trace} onClose={()=>setTrace(null)}/>}</Page>;
}
