import type { InventoryValuationAsOfReport, InventoryValuationLayerReport, InventoryValuationMonetaryKardexReport, InventoryValuationUnresolvedReport } from "@argin/inventory/valuation-reports";
import type { InventoryValuationPolicySnapshot } from "@argin/inventory/valuation-policy";
import type { InventoryValuationTraceSnapshot } from "@argin/inventory/valuation-security";
import { gregorianToJalali } from "./inventory-persian-date";
import { valuationMethodLabel } from "./inventory-valuation-workspace-format";

const money=(v:number|null,c="IRR")=>v===null?"نامشخص":`${new Intl.NumberFormat("fa-IR").format(v)} ${c}`;
const Table=({headers,rows}:{headers:string[];rows:(string|number)[][]})=><div className="valuation-table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}><bdi>{c}</bdi></td>)}</tr>)}</tbody></table></div>;

export function ValuationOverviewPanel({report}:{report:InventoryValuationAsOfReport}){return <><div className="valuation-cards"><article><span>ارزش حل‌شده</span><strong>{money(report.resolvedTotalCost)}</strong></article><article><span>ردیف نامشخص</span><strong>{report.unresolvedRowCount}</strong></article></div><Table headers={["کالا","انبار","تاریخ","روش","تعداد","ارزش","وضعیت"]} rows={report.rows.map(r=>[r.productId,r.warehouseId,gregorianToJalali(r.businessDate),valuationMethodLabel(r.method),r.quantity,money(r.totalCost,r.currency),r.totalCost===null||r.unresolvedCount?"نامشخص":"حل‌شده"])} /></>}

export function ValuationKardexPanel({report,onTrace,onNext}:{report:InventoryValuationMonetaryKardexReport;onTrace:(id:string)=>void;onNext:(cursor:string)=>void}){return <><div className="valuation-cards"><article><span>افتتاحیه</span><strong>{money(report.openingResolvedCost)}</strong></article><article><span>مانده پایان صفحه</span><strong>{money(report.closingResolvedCost)}</strong></article></div><div className="valuation-table"><table><thead><tr>{["تاریخ","Movement","تعداد","قیمت واحد","اثر ریالی","مانده ریالی","ردیابی"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{report.entries.map(r=><tr key={r.valuationEntryId}><td>{gregorianToJalali(r.businessDate)}</td><td><bdi>{r.movementId}</bdi></td><td>{r.quantity}</td><td>{r.unitCost??"نامشخص"}</td><td>{money(r.monetaryDelta,r.currency)}</td><td>{money(r.runningResolvedCost,r.currency)}</td><td><button onClick={()=>onTrace(r.movementId)}>منشأ</button></td></tr>)}</tbody></table></div>{report.nextCursor&&<button className="valuation-more" onClick={()=>onNext(report.nextCursor!)}>صفحه بعد</button>}</>}

export function ValuationLayersPanel({report}:{report:InventoryValuationLayerReport}){return <><p className="valuation-note">این جدول فقط لایه‌های باز فعلی FIFO را نشان می‌دهد و گزارش تاریخی As-of نیست.</p><Table headers={["تاریخ","کالا","انبار","مقدار اولیه","باقی‌مانده","قیمت واحد","ارزش باقی‌مانده"]} rows={report.rows.map(r=>[gregorianToJalali(r.openedBusinessDate),r.productId,r.warehouseId,r.originalQuantity,r.remainingQuantity,r.unitCost,money(r.remainingCost,r.currency)])}/></>}

export function ValuationUnresolvedPanel({report}:{report:InventoryValuationUnresolvedReport}){return <Table headers={["تاریخ","کالا","انبار","تعداد","روش","علت"]} rows={report.rows.map(r=>[gregorianToJalali(r.businessDate),r.productId,r.warehouseId,r.quantity,valuationMethodLabel(r.method),r.reason])}/>}

export function ValuationPolicyPanel({rows,readOnly}:{rows:readonly InventoryValuationPolicySnapshot[];readOnly:boolean}){return <><Table headers={["از تاریخ","روش","ارز","نسخه موتور","Revision","علت تغییر"]} rows={rows.map(p=>[gregorianToJalali(p.effectiveFrom),valuationMethodLabel(p.method),p.currency,p.strategyVersion,p.revision,p.changeReason??(p.previousPolicyId?"تغییر سیاست":"سیاست اولیه")])}/>{readOnly&&<p className="valuation-note">تغییر سیاست نیازمند مجوز مدیریت ارزش‌گذاری است.</p>}</>}

export function ValuationTracePanel({trace,onClose}:{trace:InventoryValuationTraceSnapshot;onClose:()=>void}){return <aside className="valuation-trace"><button onClick={onClose}>بستن</button><h3>ردیابی منشأ ارزش‌گذاری</h3><p>Movement: <bdi>{trace.movementId}</bdi></p><p>Policy: {valuationMethodLabel(trace.policy.method)} / Revision {trace.policy.revision}</p><p>Cost Input: {trace.costInput?money(trace.costInput.totalCost,trace.costInput.currency):"ندارد"}</p><p>Valuation Entry: {trace.entry?money(trace.entry.totalCost,trace.entry.currency):"ایجاد نشده"}</p></aside>}
