import type { PermissionDefinition } from "../domain/permission.ts";

export const defaultPermissions: PermissionDefinition[] = [
  { code: "system.full-access", module: "system", title: "دسترسی کامل سیستم", description: "مجوز مدیریتی کامل برای مدیر اصلی" },
  { code: "security.users.view", module: "security", title: "مشاهده کاربران" },
  { code: "security.users.manage", module: "security", title: "مدیریت کاربران" },
  { code: "security.roles.view", module: "security", title: "مشاهده نقش‌ها" },
  { code: "security.roles.manage", module: "security", title: "مدیریت نقش‌ها" },
  { code: "security.permissions.view", module: "security", title: "مشاهده مجوزها" },
  { code: "security.permissions.assign", module: "security", title: "انتساب مجوزها" },
  { code: "company.profile.view", module: "company", title: "مشاهده اطلاعات شرکت" },
  { code: "company.profile.manage", module: "company", title: "مدیریت اطلاعات شرکت" },
  { code: "company.profile.update-activity-type", module: "company", title: "تغییر نوع فعالیت شرکت", description: "تغییر نوع فعالیت فقط پیشنهاد الگوی کدینگ را به‌روزرسانی می‌کند" },
  { code: "company.branches.view", module: "company", title: "مشاهده شعب" },
  { code: "company.branches.manage", module: "company", title: "مدیریت شعب" },
  { code: "fiscal.years.view", module: "fiscal", title: "مشاهده سال‌های مالی" },
  { code: "fiscal.years.manage", module: "fiscal", title: "مدیریت سال‌های مالی" },
  { code: "fiscal.periods.manage", module: "fiscal", title: "مدیریت دوره‌های مالی" },
  { code: "fiscal.locks.manage", module: "fiscal", title: "مدیریت قفل‌های مالی" },
  { code: "fiscal.number-series.manage", module: "fiscal", title: "مدیریت سری شماره‌گذاری" },
  { code: "accounting.chart-of-accounts.view", module: "accounting", title: "مشاهده کدینگ حساب‌ها" },
  { code: "accounting.chart-of-accounts.create", module: "accounting", title: "ایجاد حساب" },
  { code: "accounting.chart-of-accounts.update", module: "accounting", title: "ویرایش اطلاعات حساب" },
  { code: "accounting.chart-of-accounts.change-code", module: "accounting", title: "تغییر کد حساب" },
  { code: "accounting.chart-of-accounts.move", module: "accounting", title: "تغییر والد حساب" },
  { code: "accounting.chart-of-accounts.change-status", module: "accounting", title: "فعال یا غیرفعال‌کردن حساب" },
  { code: "accounting.chart-of-accounts.delete", module: "accounting", title: "حذف حساب استفاده‌نشده" },
  { code: "accounting.chart-of-accounts.manage-settings", module: "accounting", title: "مدیریت تنظیمات کدینگ" },
  { code: "accounting.dimensions.view", module: "accounting", title: "مشاهده ابعاد حسابداری" },
  { code: "accounting.dimensions.create", module: "accounting", title: "ایجاد نوع یا عضو بُعد حسابداری" },
  { code: "accounting.dimensions.update", module: "accounting", title: "ویرایش نوع یا عضو بُعد حسابداری" },
  { code: "accounting.dimensions.change-status", module: "accounting", title: "فعال یا غیرفعال‌کردن ابعاد حسابداری" },
  { code: "accounting.dimensions.delete", module: "accounting", title: "حذف نوع یا عضو بُعد حسابداری" },
  { code: "accounting.dimensions.manage-policies", module: "accounting", title: "مدیریت سیاست‌های حساب و بُعد" },
  { code: "accounting.journal-vouchers.view", module: "accounting", title: "مشاهده اسناد حسابداری" },
  { code: "accounting.journal-vouchers.create", module: "accounting", title: "ایجاد سند حسابداری" },
  { code: "accounting.journal-vouchers.update-draft", module: "accounting", title: "ویرایش سند حسابداری پیش‌نویس" },
  { code: "accounting.journal-vouchers.delete-draft", module: "accounting", title: "حذف سند حسابداری پیش‌نویس" },
  { code: "accounting.journal-vouchers.view-history", module: "accounting", title: "مشاهده تاریخچه سند حسابداری" },
  { code: "accounting.journal-vouchers.submit", module: "accounting", title: "ارسال سند حسابداری برای تأیید" },
  { code: "accounting.journal-vouchers.approve", module: "accounting", title: "تأیید سند حسابداری" },
  { code: "accounting.journal-vouchers.reject", module: "accounting", title: "رد سند حسابداری" },
  { code: "accounting.journal-vouchers.return-to-draft", module: "accounting", title: "بازگرداندن سند حسابداری به پیش‌نویس" },
  { code: "accounting.journal-vouchers.cancel-approval", module: "accounting", title: "لغو چرخه تأیید سند حسابداری" },
  { code: "accounting.journal-vouchers.post", module: "accounting", title: "ثبت نهایی سند حسابداری" },
  { code: "accounting.journal-vouchers.reopen-for-amendment", module: "accounting", title: "بازگشایی کنترل‌شده سند برای اصلاح" },
  { code: "accounting.journal-vouchers.reverse", module: "accounting", title: "برگشت سند حسابداری ثبت‌شده" },
  { code: "accounting.reports.trial-balance.view", module: "accounting", title: "مشاهده تراز آزمایشی" },
  { code: "accounting.reports.general-ledger.view", module: "accounting", title: "مشاهده دفتر کل" },
  { code: "accounting.reports.subsidiary-ledger.view", module: "accounting", title: "مشاهده دفتر معین و گردش حساب" },
  { code: "accounting.reports.journal.view", module: "accounting", title: "مشاهده دفتر روزنامه" },
  { code: "accounting.reports.dimensions.view", module: "accounting", title: "مشاهده گزارش ابعاد حسابداری" },
  { code: "accounting.reports.export", module: "accounting", title: "خروجی‌گرفتن از گزارش‌های حسابداری" },
  { code: "master-data.parties.view", module: "master-data", title: "مشاهده اشخاص و طرف‌حساب‌ها" },
  { code: "master-data.parties.create", module: "master-data", title: "ایجاد شخص یا طرف‌حساب" },
  { code: "master-data.parties.update", module: "master-data", title: "ویرایش اطلاعات شخص یا طرف‌حساب" },
  { code: "master-data.parties.change-status", module: "master-data", title: "فعال یا غیرفعال‌کردن شخص یا طرف‌حساب" },
  { code: "master-data.parties.manage-roles", module: "master-data", title: "مدیریت نقش مشتری و تأمین‌کننده" },
  { code: "master-data.parties.import", module: "master-data", title: "ورود گروهی اشخاص" },
  { code: "master-data.parties.export", module: "master-data", title: "خروجی‌گرفتن از اطلاعات اشخاص" },
  { code: "master-data.products.view", module: "master-data", title: "مشاهده کالاها و خدمات" },
  { code: "master-data.products.create", module: "master-data", title: "ایجاد کالا یا خدمت" },
  { code: "master-data.products.update", module: "master-data", title: "ویرایش مشخصات اصلی کالا یا خدمت" },
  { code: "master-data.products.manage-identifiers", module: "master-data", title: "مدیریت شناسه‌ها و بارکدهای کالا و خدمت" },
  { code: "master-data.products.manage-units", module: "master-data", title: "مدیریت واحدها و تبدیل واحد کالا و خدمت" },
  { code: "master-data.products.manage-master-data", module: "master-data", title: "مدیریت اطلاعات تجاری، مالیاتی و عملیاتی کالا و خدمت" },
  { code: "master-data.products.change-status", module: "master-data", title: "فعال یا غیرفعال‌کردن کالا یا خدمت" },
  { code: "master-data.products.import", module: "master-data", title: "ورود گروهی کالاها و خدمات" },
  { code: "master-data.products.export", module: "master-data", title: "خروجی‌گرفتن از کالاها و خدمات" },
  { code: "master-data.products.manage-taxpayer-reference-data", module: "master-data", title: "مدیریت اطلاعات مرجع واحدهای سامانه مودیان" },
  { code: "inventory.warehouses.view", module: "inventory", title: "مشاهده انبارها" },
  { code: "inventory.warehouses.create", module: "inventory", title: "ایجاد انبار" },
  { code: "inventory.warehouses.update", module: "inventory", title: "ویرایش اطلاعات انبار" },
  { code: "inventory.warehouses.change-status", module: "inventory", title: "تغییر وضعیت انبار" },
  { code: "inventory.warehouses.manage-scope", module: "inventory", title: "مدیریت حوزه سازمانی و شعبه انبار" },
  { code: "inventory.warehouses.delete", module: "inventory", title: "حذف انبار اشتباهی و بدون وابستگی" },
  { code: "inventory.warehouses.manage-locations", module: "inventory", title: "مدیریت ناحیه‌ها و مکان‌های فیزیکی انبار" },
  { code: "inventory.warehouses.import", module: "inventory", title: "ورود گروهی انبارها" },
  { code: "inventory.warehouses.export", module: "inventory", title: "خروجی‌گرفتن از انبارها" },
  { code: "audit.entries.view", module: "audit", title: "مشاهده رویدادهای ممیزی" },
  { code: "audit.entries.record", module: "audit", title: "ثبت رویداد ممیزی" },
  { code: "approval.requests.view", module: "approval", title: "مشاهده درخواست‌های تأیید" },
  { code: "approval.requests.create", module: "approval", title: "ایجاد درخواست تأیید" },
  { code: "approval.requests.submit", module: "approval", title: "ارسال درخواست برای تأیید" },
  { code: "approval.requests.approve", module: "approval", title: "تأیید درخواست" },
  { code: "approval.requests.reject", module: "approval", title: "رد درخواست تأیید" },
  { code: "approval.requests.return-to-draft", module: "approval", title: "بازگرداندن درخواست به پیش‌نویس" },
  { code: "approval.requests.cancel", module: "approval", title: "لغو درخواست تأیید" },
  { code: "approval.requests.comment", module: "approval", title: "ثبت توضیح روی درخواست تأیید" },
];
